name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    # Disable job.
    # TODO: implement gihub pages deployment.
    if: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build:examples

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/build
